<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PatternsTfm)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Patterns.Core\Patterns.Core.csproj" />
    <ProjectReference Include="..\Patterns.Rendering\Patterns.Rendering.csproj" />
  </ItemGroup>

</Project>
