// The variables, as Companion 5 wants them: an object keyed by id. Every id the module writes is
// declared here and the tests hold both lists to each other, so a key never renders its own
// variable's name as its label (track_7 and track_8 did, once).
import { BANK_SIZES } from './state.js'

export function variableDefinitions() {
	const v = {
		air_look: 'The look on air, by name (or empty)',
		preview_look: 'The look loaded in the preview, by name (or empty)',
		pattern: 'What kind of picture is on air (Media, LedWall, ProjectionBlend…)',
	}
	for (let n = 1; n <= BANK_SIZES.look; n++) v[`look_${n}`] = `Look at place ${n} in the show's list (name, or empty)`
	for (let f = 1; f <= BANK_SIZES.look_f; f++) v[`look_f${f}`] = `Look on F${f} (name, or empty)`
	for (let n = 1; n <= 8; n++) {
		v[`lt_${n}`] = `Lower third design ${n} (name, or empty)`
		v[`person_${n}`] = `Person ${n} in the library (name, or empty)`
		v[`stinger_${n}`] = `VOG / stinger ${n} (name, or empty)`
		v[`screen_${n}`] = `Screen ${n} (its label, or empty)`
		v[`track_${n}`] = `Audio playlist track ${n} (name, or empty)`
		v[`screen_${n}_pattern`] = `Screen ${n} — the kind of picture it is showing`
		v[`screen_${n}_signal`] = `Screen ${n} — the signal result: MATCH, MISMATCH, PARTIAL (a contracted property nobody stated, round 72) or UNVERIFIED (round 65)`
		v[`screen_${n}_group`] = `Screen ${n} — its group: main, confidence, info or repeater (round 67)`
		v[`screen_${n}_audio`] = `Screen ${n} — the output its sound leaves by, the route following the picture; empty for none (round 69)`
		v[`node_${n}`] = `Node ${n} as the Nodes page lists it — its kind and its machine (or empty)`
		v[`node_${n}_kind`] = `Node ${n} — desk, caller, arcade or timer`
		v[`node_${n}_words`] = `Node ${n} — its own health line`
	}
	for (let n = 1; n <= 6; n++) {
		v[`music_${n}`] = `Break music entry ${n} (name, or empty)`
		v[`section_${n}`] = `Playlist part ${n} (name, or empty)`
	}
	for (let k = 1; k <= BANK_SIZES.cue; k++) {
		v[`cue_${k}`] = `Cue bank ${k} — number and name (1 = the standby cue, 2… the cues after it)`
		v[`cue_${k}_number`] = `Cue bank ${k} — number`
		v[`cue_${k}_name`] = `Cue bank ${k} — name`
	}
	Object.assign(v, {
		blackout: 'Blackout state',
		presenter_step: 'Presenter step number',
		presenter_count: 'Presenter step count',
		playlist: 'Playlist status',
		next_cue: 'Next scheduled cue',
		stinger: 'VOG or stinger on air (name)',
		sting_hold: 'Stinger holding the screens (name)',
		duck: 'Live duck (DUCK/off)',
		lower_third: 'Lower third on screen (name, or empty)',
		lower_third_person: 'The name the lower third on screen carries (or empty)',
		lower_third_preview: 'Lower third in the preview for a sign-off (name, or empty)',
		lower_third_preview_person: 'The name the lower third in the preview carries (or empty)',
		lower_third_default: "The show's default lower third design (★)",
		lower_third_edited: 'EDITED when the design on air differs from the edited one, else off',
		lower_third_timed: 'TIMED while the lower third on screen leaves by itself, else off (round 73)',
		lower_third_leaves_in: 'Seconds before the lower third on screen starts to leave by itself, to a tenth; empty when it stays until hidden (round 73)',
		midi_learning: 'The wire line MIDI learn waits for a control for, else empty (round 73)',
		midi_bindings: 'How many controls are bound on the MIDI surfaces (round 73)',
		midi_surfaces: 'The MIDI surfaces in the show, the open ones marked (round 73)',
		midi_words: "MIDI in one line — learning a line, or how many controls are bound on which surfaces (round 73)",
		review: 'Review on the multiview (ON/off)',
		weather: 'The weather chip on air (ON/off)',
		weather_text: 'The weather as the desk reads it ("Manchester · 18° · Light rain · wind 12 km/h")',
		weather_place: "The weather chip's place",
		weather_figure: 'The weather chip\'s figure ("18°", "14–19°")',
		weather_view: "The weather chip's view (now / day / tomorrow)",
		freeze: 'Freeze (FROZEN/off)',
		look_state: 'The look on air and whether it still is what is on the screens (LIVE / EDITED / off)',
		look_screens_off: 'How many screens have gone their own way inside the look on air',
		stream_status: "The stream in a word (the desk's own status line)",
		stream_health: "The stream's health (good / slow / trouble)",
		stream_up: 'How long the stream has been up',
		stream_fps: "The stream's frame rate",
		outputs_live: 'The outputs (LIVE/off)',
		edit_safe: 'EDIT SAFE (ON/off)',
		tone: 'The soundcheck tone (ON/off)',
		timing_offset: 'How the day is running against the plan ("11 min late")',
		timing_next_break: 'The next break',
		timing_end: 'When the day is expected to end',
		black: 'Screens faded to black on their own (how many, or off)',
		black_text: 'Screens faded to black on their own, by name ("Screen 2 · Group A")',
		black_audio: "The programme's sound is down with a fade to black (DOWN/off)",
		previous_look: 'The look LOOK BACK returns to (name, or empty)',
		audio_track: 'Audio playlist — the track on (or up next when stopped)',
		audio_next: 'Audio playlist — the track after it',
		audio_n: 'Audio playlist — the place of the track on (1…)',
		audio_count: 'Audio playlist — how many tracks',
		audio_position: 'Audio playlist — where the track is (m:ss)',
		audio_remaining: 'Audio playlist — what is left of the track (m:ss)',
		audio_state: 'Audio playlist (PLAYING / stopped)',
		audio_level: 'Audio playlist — the level (0–125 %), what the knob steps from (round 74)',
		program: 'What is on air, by name',
		cue_armed: 'Cue stack armed (ARMED/off)',
		cue_hold: 'Cue stack HOLD (HOLD/off)',
		cue_seq: 'Cue stack sequence number',
		cue_standby_number: 'Standby cue number',
		cue_standby_name: 'Standby cue name',
		cue_next_number: 'Next cue number (after the standby)',
		cue_next_name: 'Next cue name',
		cue_previous_number: 'Previous cue number',
		cue_previous_name: 'Previous cue name',
		cue_last_outcome: 'Outcome of the last cue (Done / Requested / Failed / FailedLate / Refused…)',
		cue_last_pending: 'Device receipts the last cue still waits for (0 when settled)',
		cue_confirm: 'The confirmation GO is waiting for (or empty)',
		last_error: 'Last ERR line from Patterns',
		music: 'Break music — the track Spotify reports',
		music_state: 'Break music (PLAYING / paused)',
		music_level: 'Break music — the Spotify device level',
		music_device: 'Break music — the Spotify device',
		health: 'Machine health line',
		machine_cpu: 'Machine CPU (percent)',
		machine_fps: 'Output frame rate',
		machine_power: 'Power (mains / BATTERY)',
		machine_advice: 'Machine-page suggestions needing attention',
		machine_render_faults: 'Render faults in the last minute (frames whose draw threw; the last good picture was shown instead)',
		machine_faulting: 'An output is faulting right now (FAULT / ok)',
		machine_live_age: 'Live input age: the oldest camera or feed picture an output drew in the last minute, decoder to frame (ms, or n/a with none drawn) — the IMAG number',
		machine_inventory: 'The machine as Windows describes it, in one line: the card and its driver, the displays, the audio outputs, the power plan (round 65.9)',
		machine_rig: 'The known-good rig: not saved, unchanged since …, or N changes since … (round 65.9)',
		commissioning: 'The commissioning flow\'s headline: commissioned, or N of 7 stages green and where it stands (round 65.10)',
		commissioning_next: 'The commissioning flow\'s next step in the desk\'s words; empty once commissioned (round 65.10)',
		eye_headline: "God's Eye — the picture's headline: the worst thing and what is wrong, or all green (round 66)",
		eye_worst: "God's Eye — the worst thing by name and what is wrong, or empty when nothing is red or amber (round 66)",
		eye_problems: "God's Eye — how many things in the picture are red or amber (round 66)",
		eye_focus: "God's Eye — the id the operator's eye is on, or empty for the whole picture (round 66)",
		take_next: "The one-shot the next TAKE arrives by — 'WIPE LEFT 800 ms', 'STING Whoosh' — or empty for the show's own transition (round 67)",
		take_scope: "The wall's take scope as the desk's picker has it — every screen, the focused screen, the ticked screens, the ticked groups (round 67)",
		take_words: "What the next TAKE will do — '→ 1 · Left, 2 · Right · 1 outside the scope keeps its picture' — or why it is refused (round 67)",
		take_landing: "A TAKE waiting under a video sting — the ticket the press froze: '→ 1 · Left, 2 · Right when \'Whoosh\' ends' while the clip runs, else empty (round 72)",
		editing_target: "What the desk is editing — 'the programme', or a screen's own preview by its label (round 73)",
		editing_kind: "The kind of picture under the desk's editors — Grid, Fractal, Particles, Media… (round 73)",
		editing_editor: 'The page that edits it — Pattern, Fractals, Particles, Reactive, Media or Branding (round 73)',
		editing_library: 'The Library tile last put on the editing target, by name, or empty (round 73)',
		machine_memory_pressure: 'Media memory pressure: none / elevated / high / critical — the rung the desk\'s memory ladder stands on (pictures, frame pools, retiring frames and decks against their budget)',
		machine_memory_held: "What the desk holds in memory and why — '4 held (312 MB): 2 on air, 1 armed, 1 idle — the first lets go in 43 s' (round 69)",
		machine_gpu_cache: "Skia's GPU cache as governed — 'GPU cache 48 MB of 128 MB (212 resources)', or 'GPU cache: no GPU context (software rendering)' (round 69)",
		inputs_pending: "A reopen staged under a source on air ('Low latency change pending — Cam Link 4K is on air; applies when it leaves the air or the outputs go off air.'), or empty",
		devices_failing: 'Interactive devices whose last word was a failure (count)',
		device_last_reply: "The newest reply from any Interactive device ('Projector: POWR: OK — accepted', or empty)",
		device_last_failure: "The newest failure from any Interactive device ('Projector: INPUT HDMI 2 — no answer in 2 s', or empty)",
		web_page: 'The web page on air (its nickname or host, or empty)',
		web_title: "The web page on air — the page's title",
		web_service: 'The web page on air — its service (YouTube, Google Slides, PowerPoint…)',
		web_fps: "The web page on air — frames it delivered in the last second (a video's rate; empty for a still page)",
		web_path: "The web page on air — how its picture reaches the glass: the buffer, the decode time, frames delivered → presented (round 68)",
		web_smoothing: "The web page on air — its smoothing: 'smooth 2 (67 ms)', 'low latency', 'auto → smooth 2 (67 ms)' (round 68)",
		web_latency: "The web page on air — the delay its smoothing buffer adds, in ms; 0 ms at low latency (round 68)",
		web_underruns: "The web page on air — stalls: times its buffer ran dry while a video played (round 68)",
		web_capture: "The web page on air — what the browser is asked to hand over: 'captured at 1280×720 · q60' (round 68)",
		audio_routing: 'The routing matrix (which soundtrack goes where): ON or off',
		audio_routing_words: 'The routing matrix in a line — what is routed where and how a VOG behaves',
		audio_follow: "The sound follows the picture (ON/off): each screen's named output carries what its picture is (round 69)",
		audio_follow_words: 'What the picture routes where — "Sound follows the picture on 2 screens: Main wall → Main HDMI (the programme), …" (round 69)',
		web_vt: "The web page on air — its video: armed and where from, or its clock (1:23 / 4:56 · playing), ADVERT while one shows",
		web_armed: 'The armed web VT anywhere on the desk — "VT armed at 1:23" — or empty',
		web_armed_page: 'The page that armed VT is on (its nickname or host), or empty',
		deck_page: 'The deck on air — the page on show (or empty)',
		deck_count: 'The deck on air — how many pages (or empty)',
		deck_file: 'The deck on air — its file (or empty)',
		video_file: 'The clip on air — its file (or empty)',
		video_tag: 'The clip on air — VT, AUDIO, STINGER CLIP or PLAYLIST',
		video_position: 'The clip on air — where it is (m:ss)',
		video_length: 'The clip on air — how long it is (m:ss)',
		video_remaining: 'The clip on air — what is left (m:ss)',
		video_remaining_seconds: 'The clip on air — what is left, in seconds',
		video_text: 'The caller\'s VT clock as the desk reads it',
		video_chip: 'The caller\'s VT clock chip ("VT 2:28")',
		video_call: 'The caller\'s word in the clip\'s last ten seconds ("OUT IN 7")',
		install: 'The install schedule (ON/off)',
		install_programme: 'The install — the programme on',
		install_over: 'The install — the announcement or advert on',
		install_next: 'The install — the next change',
		install_status: "The install page's line",
		clock: 'The clock overlay (ON/off)',
		clock_hours: 'The clock overlay — 12 or 24',
		clock_text: 'The clock overlay — what it reads now',
		clock_seconds: 'The clock overlay — seconds shown (ON/off)',
		clock_date: 'The clock overlay — the date line (ON/off)',
		message: 'The message overlay (ON/off)',
		message_text: 'The message overlay — the words',
		message_scroll: 'The message overlay — SCROLL or still',
		countdown: 'The countdown — running, over or off',
		countdown_text: 'The countdown as the desk reads it ("12:34 · DOORS IN")',
		countdown_remaining_seconds: 'The countdown — what is left, in seconds',
		countdown_label: 'The countdown — the words over the digits',
		countdown_target: 'The countdown — its target (19:30, or 15 min)',
		logo: 'The logo overlay (ON/off)',
		pip: 'The PiP inset (ON/off)',
		overlays_text: 'The overlays in one line',
		desk_version: 'The desk — its version, as it said on the link',
		show: 'The show that is loaded, by name',
		nodes_count: 'How many nodes the desk hears on the beacon right now',
		nodes_text: 'The nodes the desk hears, in one line',
		twin_role: 'The twin — off, main or standby',
		twin_phase: 'The twin — listening, connecting, inStep, mainSilent, tookOver, refused',
		twin_words: "The twin — the Machine page's line",
		twin_holder: 'The twin — the standby that has the show, or empty',
		twin_clocks: 'The twin — each peer\'s clock against this desk\'s',
		stage_timer: 'The stage timer as the speaker reads it',
		stage_phase: 'The stage timer — idle, running, paused or over',
		stage_colour: 'The stage timer — its colour word (green, amber, red)',
		stage_label: 'The stage timer — its label',
		stage_remaining_seconds: 'The stage timer — what is left, in seconds',
		stage_progress: 'The stage timer — how far through, in percent',
		stage_segment: 'The running order — the cue running',
		stage_next: 'The running order — the cue next',
		stage_pending: "The speaker's stage page — a message waiting for its ACK, or empty",
		stage_pending_crew: "The crew's stage page — a message waiting for its ACK, or empty",
		// Round 74: where the desk is, and the Navigator's keys.
		desk_page: "The desk — the page it is on (Run while the Run surface is up)",
		desk_rail: 'The desk — the rail of its page (SHOW, PLAN, BUILD, SETUP, ADMIN)',
		desk_settings: "The desk — the settings column's title while it is open, or empty",
		desk_back: 'The desk — the page BACK returns to, or empty',
		desk_selection: 'The desk — the thing selected on its page, in words, or empty',
		desk_where: 'The desk — where it is, in one line',
		desk_decks: "The decks — each deck's name and where its navigator is",
		last_action: 'The last action the desk did while this connection was recording, as the line that reproduces it',
		nav_level: 'Navigator — rails, pages, page, menu or drawer',
		nav_rail: 'Navigator — the rail on the keys',
		nav_page: 'Navigator — the page on the keys',
		nav_menu: "Navigator — the thing's menu on the keys (the words after MENU)",
		nav_title: 'Navigator — the title of this level',
		nav_where: 'Navigator — where the keys are, as crumbs (what the desk\'s Remote page shows for this deck)',
		nav_range: 'Navigator — "1–24 of 40" when the level has more entries than keys, or empty',
		nav_count: 'Navigator — how many entries this level has',
		nav_mode: 'Navigator — MENU or RUN',
		nav_follow: 'Navigator — FOLLOW or off',
		nav_text: 'Navigator — the words the next text-taking key uses',
		nav_reply: "Navigator — the desk's answer to the last key pressed",
		nav_pages: "Navigator — the rail's pages, in one line",
	})
	for (let n = 1; n <= 24; n++) {
		v[`nav_slot_${n}`] = `Navigator — slot ${n}: its words (▸ a drawer, … takes a text; empty with nothing on it)`
		v[`nav_slot_${n}_wire`] = `Navigator — slot ${n}: the line it sends`
		v[`nav_slot_${n}_detail`] = `Navigator — slot ${n}: its detail, or why it cannot be chosen`
		v[`nav_slot_${n}_group`] = `Navigator — slot ${n}: the group it sits in`
	}
	const out = {}
	for (const [id, name] of Object.entries(v)) out[id] = { name }
	return out
}
