using Patterns.Core.Model;

namespace Patterns.Core.Services;

/// <summary>
/// The wire the other way round: a show action written as the line that reproduces it (round
/// 74). The desk pushes these to a deck that is recording (Companion's Action Recorder —
/// RECORD ON on the wire), the menus and the assistant can say what a press was in the wire's
/// own words, and a test round-trips the wire's whole vocabulary through here and the parser.
/// A kind the wire has no line for — TAKE and CUT (a wire cannot take a half-built preview),
/// a note — writes "" and is not recorded. Round 75: so does a kind whose target is a secret
/// (<see cref="ActionSpec.CarriesSecret"/> — UPDATE APPLY and RESTART carry the admin passcode);
/// a deck recording the desk never hears it, and a line a deck could not replay without the
/// passcode is no loss.
/// </summary>
public static class WireWriter
{
    public static string Line(ShowAction a)
    {
        if (ActionSpec.CarriesSecret(a.Kind)) return "";
        var t = a.Target ?? "";
        var v = a.Value ?? "";
        static string Join(params string[] parts) => string.Join(' ', parts.Where(p => p.Length > 0));
        return a.Kind switch
        {
            ShowActionKind.OutputsOn => "GO",
            ShowActionKind.OutputsOff => "OUTPUTS OFF",
            ShowActionKind.Identify => "IDENTIFY",
            ShowActionKind.PresenterNext => "NEXT",
            ShowActionKind.PresenterPrev => "BACK",
            ShowActionKind.StopAll => "STOPALL",
            ShowActionKind.CueGo => Join("CUE GO", t),
            ShowActionKind.CueStandby => t.ToUpperInvariant() switch { "NEXT" => "CUE STANDBY NEXT", "PREV" => "CUE STANDBY BACK", _ => Join("CUE STANDBY", t) },
            ShowActionKind.CueHoldOn => "CUE HOLD ON",
            ShowActionKind.CueHoldOff => "CUE HOLD OFF",
            ShowActionKind.ListArm => t.Equals("caller", StringComparison.OrdinalIgnoreCase) ? "CUE ARM ON" : "",
            ShowActionKind.ListDisarm => t.Equals("caller", StringComparison.OrdinalIgnoreCase) ? "CUE ARM OFF" : "",
            ShowActionKind.CueAdd => Join("CUE ADD", v),
            ShowActionKind.CueDelete => Join("CUE DELETE", v),
            ShowActionKind.SpotifyPlay => Join("MUSIC PLAY", t),
            ShowActionKind.SpotifyPause => "MUSIC PAUSE",
            ShowActionKind.SpotifyNext => "MUSIC SKIP",
            ShowActionKind.SpotifyVolume => Join("MUSIC VOL", v),
            ShowActionKind.BlackoutOn => "BLACKOUT ON",
            ShowActionKind.BlackoutOff => "BLACKOUT OFF",
            ShowActionKind.BlackoutToggle => "BLACKOUT",
            ShowActionKind.ApplyLookHotkey => Join("LOOK", t),
            ShowActionKind.ApplyLook => Join("LOOK", t),
            ShowActionKind.ApplyLookToPreview => Join("PVW LOOK", t),
            ShowActionKind.LookBack => Join("LOOKBACK", v),
            ShowActionKind.LookSave => Join("LOOK SAVE", v),
            ShowActionKind.LookUpdate => Join("LOOK UPDATE", v),
            ShowActionKind.LookDelete => Join("LOOK DELETE", v),
            ShowActionKind.ScreenOn => Join("SCREEN", t, "ON"),
            ShowActionKind.ScreenOff => Join("SCREEN", t, "OFF"),
            ShowActionKind.ScreenToggle => Join("SCREEN", t),
            ShowActionKind.ScreenLook => Join("SCREEN", t, "LOOK", v),
            ShowActionKind.ScreenPreset => Join("SCREEN", t, "PRESET", v),
            ShowActionKind.ScreenProgram => Join("SCREEN", t, "PGM"),
            ShowActionKind.ScreenRole => Join("SCREEN", t, "ROLE", v),
            ShowActionKind.ScreenLabel => Join("SCREEN", t, "LABEL", v),
            ShowActionKind.ScreenAudio => Join("SCREEN", t, "AUDIO", v),
            ShowActionKind.AudioFollow => Join("AUDIO FOLLOW", v),
            ShowActionKind.ScreenSignal => Join("SCREEN", t, "SIGNAL", v),
            ShowActionKind.ScreenTestRoute => Join("SCREEN", t, "TESTROUTE", v),
            ShowActionKind.ScreenReceived => Join("SCREEN", t, "RECEIVED", v),
            ShowActionKind.ScreenPattern => Join("SCREEN", t, "PATTERN", v),
            ShowActionKind.ScreenTake => Join("SCREEN", t, "TAKE"),
            ShowActionKind.ScreenCut => Join("SCREEN", t, "CUT"),
            ShowActionKind.ScreenStageLook => t.Length == 0 ? "" : Join("SCREEN", t, "PVW LOOK", v),
            ShowActionKind.ScreenStagePreset => t.Length == 0 ? Join("PVW PRESET", v) : Join("SCREEN", t, "PVW PRESET", v),
            ShowActionKind.ScreenStagePattern => t.Length == 0 ? Join("PVW PATTERN", v) : Join("SCREEN", t, "PVW PATTERN", v),
            ShowActionKind.ScreenStageProgram => t.Length == 0 ? "" : Join("SCREEN", t, "PVW PROGRAM"),
            ShowActionKind.ScreenStageReset => t.Length == 0 ? "PVW RESET" : Join("SCREEN", t, "PVW RESET"),
            ShowActionKind.ScreenStageLibrary => t.Equals("FOCUSED", StringComparison.OrdinalIgnoreCase) ? Join("LIBRARY", v) : t.Length == 0 ? Join("PVW LIBRARY", v) : Join("SCREEN", t, "PVW LIBRARY", v),
            ShowActionKind.ScreenToPreview => t.Length == 0 ? "PREVIEW" : Join("SCREEN", t, "PVW"),
            ShowActionKind.ScreenLock => Join("LOCK", t, "ON"),
            ShowActionKind.ScreenUnlock => Join("LOCK", t, "OFF"),
            ShowActionKind.ScreenLockToggle => Join("LOCK", t),
            ShowActionKind.CanvasOn => Join("GROUP", t, "ON"),
            ShowActionKind.CanvasOff => Join("GROUP", t, "OFF"),
            ShowActionKind.RigSaveKnownGood => Join("RIG SAVE", v),
            ShowActionKind.EyeFocus => Join("EYE FOCUS", v),
            ShowActionKind.EyeNext => "EYE NEXT",
            ShowActionKind.EyePrev => "EYE PREV",
            ShowActionKind.EyeLens => Join("EYE LENS", v),
            ShowActionKind.EyeReset => "EYE RESET",
            ShowActionKind.NextTransition => v.Equals("CLEAR", StringComparison.OrdinalIgnoreCase) ? "TAKE NEXT" : Join("TAKE NEXT", v),
            ShowActionKind.MidiLearn => Join("MIDI LEARN", v),
            ShowActionKind.MidiLearnOff => "MIDI LEARN OFF",
            ShowActionKind.MidiForget => Join("MIDI FORGET", v),
            ShowActionKind.NavPage => Join("NAV", t, v),
            ShowActionKind.NavBack => "NAV BACK",
            ShowActionKind.NavHome => "NAV HOME",
            ShowActionKind.NavSettings => Join("NAV SETTINGS", v),
            ShowActionKind.AudioPlay => Join("AUDIO PLAY", t),
            ShowActionKind.AudioStop => "AUDIO STOP",
            ShowActionKind.AudioNext => "AUDIO NEXT",
            ShowActionKind.AudioPrev => "AUDIO PREV",
            ShowActionKind.AudioVolume => Join("AUDIO VOL", v),
            ShowActionKind.ToneOn => "TONE ON",
            ShowActionKind.ToneOff => "TONE OFF",
            ShowActionKind.DuckOn => "DUCK ON",
            ShowActionKind.DuckOff => "DUCK OFF",
            ShowActionKind.DuckToggle => "DUCK",
            ShowActionKind.LowerThirdShow => t.Length == 0 ? Join("PERSON", v) : v.Length == 0 ? Join("LT", t) : Join("LT", t, "WITH", v),
            ShowActionKind.LowerThirdShowFor => v.Equals("STAY", StringComparison.OrdinalIgnoreCase) ? Join("LT", t, "STAY") : Join("LT", t, "FOR", v),
            ShowActionKind.LowerThirdHold => Join("LT", t, "HOLD", v),
            ShowActionKind.LowerThirdHide => "LT OFF",
            ShowActionKind.LowerThirdPreview => t.Length == 0 ? Join("LT PREVIEW WITH", v) : v.Length == 0 ? Join("LT PREVIEW", t) : Join("LT PREVIEW", t, "WITH", v),
            ShowActionKind.LowerThirdPreviewOff => "LT PREVIEW OFF",
            ShowActionKind.LowerThirdTake => "LT TAKE",
            ShowActionKind.LowerThirdUpdate => "LT UPDATE",
            ShowActionKind.LowerThirdNew => t.Length == 0 ? Join("LT NEW", v) : Join("LT NEW", v, "FROM", t),
            ShowActionKind.WebKey => t.Length == 0 ? Join("WEB KEY", v) : Join("WEB KEY", v, "ON", t),
            ShowActionKind.WebClick => t.Length == 0 ? Join("WEB CLICK", v) : Join("WEB CLICK", v, "ON", t),
            ShowActionKind.WebType => Join("WEB TYPE", v),
            ShowActionKind.WebReload => Join("WEB RELOAD", t),
            ShowActionKind.WebOpen => t.Length == 0 ? Join("WEB OPEN", v) : Join("WEB OPEN", v, "ON", t),
            ShowActionKind.WebArm => v.Equals("off", StringComparison.OrdinalIgnoreCase) ? Join("WEB DISARM", t) : t.Length == 0 ? Join("WEB ARM", v) : Join("WEB ARM", v, "ON", t),
            ShowActionKind.WebMark => t.Length == 0 ? Join("WEB MARK", v) : Join("WEB MARK", v, "ON", t),
            ShowActionKind.DeckNext => "DECK NEXT",
            ShowActionKind.DeckPrev => "DECK PREV",
            ShowActionKind.DeckPage => v.Equals("last", StringComparison.OrdinalIgnoreCase) ? "DECK LAST" : Join("DECK PAGE", v),
            ShowActionKind.VideoToEnd => Join("VIDEO END", v),
            ShowActionKind.VideoRestart => "VIDEO RESTART",
            ShowActionKind.DeviceSend => Join("DEVICE", t, v),
            ShowActionKind.Announce => Join("ANNOUNCE", v),
            ShowActionKind.AnnounceOff => "ANNOUNCE OFF",
            ShowActionKind.AdvertPlay => Join("ADVERT", t),
            ShowActionKind.AdvertOff => "ADVERT OFF",
            ShowActionKind.ScheduleOn => "SCHEDULE ON",
            ShowActionKind.ScheduleOff => "SCHEDULE OFF",
            ShowActionKind.UpdateApply => Join("UPDATE APPLY", t),
            ShowActionKind.Restart => Join("RESTART", t),
            ShowActionKind.ClockOn => "CLOCK ON",
            ShowActionKind.ClockOff => "CLOCK OFF",
            ShowActionKind.ClockToggle => "CLOCK",
            ShowActionKind.ClockFormat => Join("CLOCK", v),
            ShowActionKind.ClockSeconds => Join("CLOCK SECONDS", v),
            ShowActionKind.ClockDate => Join("CLOCK DATE", v),
            ShowActionKind.MessageOn => Join("MESSAGE ON", v),
            ShowActionKind.MessageOff => "MESSAGE OFF",
            ShowActionKind.MessageToggle => "MESSAGE",
            ShowActionKind.MessageScroll => Join("MESSAGE SCROLL", v),
            ShowActionKind.CountdownStart => Join("COUNTDOWN", v),
            ShowActionKind.CountdownTo => Join("COUNTDOWN TO", v),
            ShowActionKind.CountdownStop => "COUNTDOWN STOP",
            ShowActionKind.CountdownLabel => Join("COUNTDOWN LABEL", v),
            ShowActionKind.LogoOn => "LOGO ON",
            ShowActionKind.LogoOff => "LOGO OFF",
            ShowActionKind.LogoToggle => "LOGO",
            ShowActionKind.PipOn => "PIP ON",
            ShowActionKind.PipOff => "PIP OFF",
            ShowActionKind.PipToggle => "PIP",
            ShowActionKind.OverlaysOff => "OVERLAYS OFF",
            ShowActionKind.PatternKind => Join("PATTERN", v),
            ShowActionKind.PatternPreset => Join("PRESET", v),
            ShowActionKind.PresetSave => Join("PRESET SAVE", v),
            ShowActionKind.WeatherOn => "WEATHER ON",
            ShowActionKind.WeatherOff => "WEATHER OFF",
            ShowActionKind.WeatherToggle => "WEATHER",
            ShowActionKind.WeatherView => Join("WEATHER", v),
            ShowActionKind.ReviewOn => "REVIEW ON",
            ShowActionKind.ReviewOff => "REVIEW OFF",
            ShowActionKind.ReviewToggle => "REVIEW",
            ShowActionKind.FreezeOn => "FREEZE ON",
            ShowActionKind.FreezeOff => "FREEZE OFF",
            ShowActionKind.FreezeToggle => "FREEZE",
            ShowActionKind.FadeToBlack => Join("FADE", v, t),
            ShowActionKind.FadeUp => Join("FADE UP", v, t),
            ShowActionKind.TwinTakeOver => v.Equals("force", StringComparison.OrdinalIgnoreCase) ? "TWIN TAKEOVER FORCE" : "TWIN TAKEOVER",
            ShowActionKind.TwinStandBy => "TWIN STANDBY",
            ShowActionKind.TwinTakeBack => "TWIN TAKEBACK",
            ShowActionKind.ShowLockOn => "SHOWLOCK ON",
            ShowActionKind.ShowLockOff => "SHOWLOCK OFF",
            ShowActionKind.CalibrateRun => Join("CALIBRATE RUN", v),
            ShowActionKind.CalibrateCancel => "CALIBRATE CANCEL",
            ShowActionKind.CalibrateDemo => "CALIBRATE DEMO",
            ShowActionKind.CalibrateApply => "CALIBRATE APPLY",
            ShowActionKind.CalibrateUndo => "CALIBRATE UNDO",
            ShowActionKind.TimerPause => "TIMER PAUSE",
            ShowActionKind.TimerResume => "TIMER RESUME",
            ShowActionKind.TimerAdd => v.StartsWith('-') ? Join("TIMER MINUS", v.TrimStart('-')) : Join("TIMER ADD", v.TrimStart('+')),
            ShowActionKind.TimerFlash => "TIMER FLASH",
            ShowActionKind.StageMessage => t.Equals("crew", StringComparison.OrdinalIgnoreCase) ? Join("STAGE CREW", v) : Join("STAGE MESSAGE", v),
            ShowActionKind.StageClear => "STAGE CLEAR",
            ShowActionKind.StageAck => Join("STAGE ACK", v),
            ShowActionKind.ArcadeStart => Join("ARCADE START", v),
            ShowActionKind.ArcadeStop => "ARCADE STOP",
            ShowActionKind.ArcadePause => "ARCADE PAUSE",
            ShowActionKind.ArcadeResume => "ARCADE RESUME",
            ShowActionKind.ArcadeAttract => Join("ARCADE ATTRACT", v),
            ShowActionKind.ArcadeKey => Join("ARCADE KEY", v),
            ShowActionKind.ArcadeSize => Join("ARCADE SIZE", v),
            ShowActionKind.ArcadeNdi => Join("ARCADE NDI", v),
            ShowActionKind.ArcadeName => Join("ARCADE NAME", v),
            ShowActionKind.ArcadeWindow => Join("ARCADE WINDOW", v),
            ShowActionKind.PlayAdd => Join("PLAY ADD", v),
            ShowActionKind.PlayOpen => v.Equals("next", StringComparison.OrdinalIgnoreCase) ? "PLAY NEXT" : Join("PLAY OPEN", v),
            ShowActionKind.PlayClose => "PLAY CLOSE",
            ShowActionKind.PlayReveal => "PLAY REVEAL",
            ShowActionKind.PlayShow => v.Equals("off", StringComparison.OrdinalIgnoreCase) ? "PLAY HIDE" : Join("PLAY SHOW", v),
            ShowActionKind.PlayMessage => Join("PLAY MESSAGE", v),
            ShowActionKind.PlayApprove => v.Equals("all", StringComparison.OrdinalIgnoreCase) ? "PLAY APPROVE" : Join("PLAY APPROVE", v),
            ShowActionKind.PlayReject => Join("PLAY REJECT", v),
            ShowActionKind.PlayAuto => Join("PLAY AUTO", v),
            ShowActionKind.PlayPath => Join("PLAY PATH", v),
            ShowActionKind.PlayDraughts => v.Equals("reset", StringComparison.OrdinalIgnoreCase) ? "PLAY DRAUGHTS" : Join("PLAY DRAUGHTS", v),
            ShowActionKind.PlayRoom => v.Equals("new", StringComparison.OrdinalIgnoreCase) ? "PLAY NEW" : "PLAY RESET",
            ShowActionKind.PlayExport => "PLAY EXPORT",
            ShowActionKind.RigDayOn => "RIGDAY ON",
            ShowActionKind.RigDayOff => "RIGDAY OFF",
            ShowActionKind.AlignStart => Join("ALIGN START", v),
            ShowActionKind.AlignStop => "ALIGN STOP",
            ShowActionKind.AlignNext => "ALIGN NEXT",
            ShowActionKind.AlignPrev => "ALIGN PREV",
            ShowActionKind.AlignNudge => Join("ALIGN NUDGE", v),
            ShowActionKind.AlignSnap => "ALIGN SNAP",
            ShowActionKind.AudienceOn => Join("AUDIENCE ON", v),
            ShowActionKind.AudienceOff => "AUDIENCE OFF",
            ShowActionKind.StreamStart => "STREAM ON",
            ShowActionKind.StreamStop => "STREAM OFF",
            ShowActionKind.PlaylistPart => Join("SECTION", t),
            ShowActionKind.StingerFire => v.Equals("vog", StringComparison.OrdinalIgnoreCase) ? Join("VOG", t) : v.Equals("sting", StringComparison.OrdinalIgnoreCase) ? Join("STING", t) : Join("STINGER", t),
            ShowActionKind.StingerStop => "STINGER STOP",
            ShowActionKind.RunMonitor => Join("RUN MONITOR", t),
            ShowActionKind.RunMonitorOff => "RUN MONITOR OFF",
            _ => "",
        };
    }
}
