<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PatternsTfm)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.46.0" />
    <ProjectReference Include="..\Patterns.Core\Patterns.Core.csproj" />
  </ItemGroup>

</Project>
